# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "lane for android firebase app distribution"
  lane :distribute_with_firebase do
    sh "flutter build apk --release --build-name=1.0.1 --build-number=2 --no-tree-shake-icons"
    puts "You have just built the apk ❤ ✨ 👸"
    puts "Now you are starting distributing to firebase app distribution ❤ ✨ 👸"
    firebase_app_distribution(
    app: "1:117733279067:android:f09adf4ca0bbfd4bbe067e",
    testers: "yaranaserelniny30999@gmail.com",
    android_artifact_type: "APK",
    firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
    android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
    release_notes: "secure groups password, this distribution is runned by github actions",
    )
    puts "Everything works fine ❤ ✨ 👸 ✔"
  end

end